"""Hospital-level summary: coordinates, multi-source pricing with provenance."""

import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Query

from app.api.deps import DbDep

router = APIRouter()

# Load pre-computed payment table (generated by scripts/generate_payment_table.py)
_PAYMENT_TABLE_PATH = (
    Path(__file__).resolve().parent.parent.parent.parent
    / "data"
    / "az-data"
    / "plan_payment_table.json"
)
_PAYMENT_TABLE: list[dict[str, Any]] = []
if _PAYMENT_TABLE_PATH.exists():
    _PAYMENT_TABLE = json.loads(_PAYMENT_TABLE_PATH.read_text())

# Verified hospital coordinates (real addresses)
_HOSPITAL_INFO: dict[str, dict[str, Any]] = {
    "Massachusetts General Hospital": {"id": "mgh", "lat": 42.3632, "lng": -71.0686},
    "Brigham and Women's Hospital": {"id": "brigham", "lat": 42.3358, "lng": -71.1065},
    "Beth Israel Deaconess Medical Center": {"id": "bidmc", "lat": 42.3389, "lng": -71.1063},
    "Boston Medical Center": {"id": "bmc", "lat": 42.3346, "lng": -71.0721},
    "Tufts Medical Center": {"id": "tufts", "lat": 42.3495, "lng": -71.0636},
    "Brigham and Women's Faulkner": {"id": "faulkner", "lat": 42.3082, "lng": -71.1271},
    "Boston Children's Hospital": {"id": "childrens", "lat": 42.3375, "lng": -71.1064},
    "Dana-Farber Cancer Institute": {"id": "dana_farber", "lat": 42.3382, "lng": -71.1068},
    "BMC Brighton (Formerly St. Elizabeth's)": {
        "id": "bmc_brighton",
        "lat": 42.3545,
        "lng": -71.1525,
    },
    "Atrius Health / Harvard Vanguard": {"id": None, "lat": 42.3415, "lng": -71.1006},
    "VA Boston Healthcare System": {"id": None, "lat": 42.3340, "lng": -71.1100},
    "Faulkner Hospital": {"id": None, "lat": 42.3082, "lng": -71.1271},
    # Cambridge + derm expansion
    "Mount Auburn Hospital": {"id": "mtauburn", "lat": 42.3738, "lng": -71.1284},
    "CHA Cambridge Hospital": {"id": "cha", "lat": 42.3667, "lng": -71.1050},
    "Franciscan Childrens": {"id": "franciscan", "lat": 42.3540, "lng": -71.1530},
}


@router.get("")
def list_hospitals(
    db: DbDep,
    cpt: str = Query("45378", description="CPT code for pricing"),
    specialty: str | None = Query(None, description="Filter providers by specialty"),
) -> list[dict[str, Any]]:
    """Return one entry per hospital with coordinates and all price sources."""
    # Count doctors per hospital, optionally filtered by specialty
    match_filter: dict[str, Any] = {"hospital": {"$exists": True, "$ne": ""}}
    if specialty:
        match_filter["specialties"] = specialty
    pipeline = [
        {"$match": match_filter},
        {"$group": {"_id": "$hospital", "doctor_count": {"$sum": 1}}},
    ]
    counts = {h["_id"]: h["doctor_count"] for h in db["providers"].aggregate(pipeline)}

    # Get pricing for requested CPT
    rates_by_id = {}
    for rate in db["hospital_rates"].find({"cpt": cpt}):
        rates_by_id[rate["hospital_id"]] = rate

    # Build hospital set: union of provider-affiliated + rate-bearing hospitals
    # This ensures hospitals show up even when providers lack hospital affiliation (derm)
    all_hospital_names: set[str] = set(counts.keys())
    for name, info in _HOSPITAL_INFO.items():
        hid = info.get("id")
        if hid and hid in rates_by_id:
            all_hospital_names.add(name)

    results = []
    for name in all_hospital_names:
        info = _HOSPITAL_INFO.get(name, {})
        lat = info.get("lat")
        lng = info.get("lng")
        if lat is None or lng is None:
            continue
        hid = info.get("id")
        rate = rates_by_id.get(hid, {}) if hid else {}
        count = counts.get(name, 0)
        results.append(
            {
                "name": name,
                "hospital_id": hid,
                "lat": lat,
                "lng": lng,
                "doctor_count": count,  # 0 if hospital has rates but no affiliated providers
                # Payer-specific negotiated rates
                "bcbs_price": rate.get("bcbs_price"),
                "bcbs_source": rate.get("bcbs_source", ""),
                "bcbs_plan": rate.get("bcbs_plan", ""),
                "aetna_price": rate.get("aetna_price"),
                "aetna_source": rate.get("aetna_source", ""),
                "harvard_pilgrim_price": rate.get("harvard_pilgrim_price"),
                "hp_plan_name": rate.get("hp_plan_name", ""),
                "hp_source": rate.get("hp_source", ""),
                "uhc_price": rate.get("uhc_price"),
                "uhc_source": rate.get("uhc_source", ""),
                # CMS charge types
                "de_identified_min": rate.get("de_identified_min"),
                "de_identified_max": rate.get("de_identified_max"),
                "gross_charge": rate.get("gross_charge"),
                "discounted_cash": rate.get("discounted_cash"),
                # Cross-validation: TiC insurer-side
                "bcbs_tic_rate": rate.get("bcbs_tic_rate"),
                "bcbs_tic_billing_class": rate.get("bcbs_tic_billing_class", ""),
                # Integrity metadata
                "billing_class": rate.get("billing_class", "unknown"),
                "setting": rate.get("setting", ""),
                "rate_methodology": rate.get("rate_methodology", ""),
                # Benchmarks
                "turquoise_bundled_price": rate.get("turquoise_bundled_price"),
                "turquoise_quality_rating": rate.get("turquoise_quality_rating"),
                "masscomparecare_total_paid": rate.get("masscomparecare_total_paid"),
                # FAIR Health component breakdown
                "fh_physician_in_network": rate.get("fh_physician_in_network"),
                "fh_anesthesia_in_network": rate.get("fh_anesthesia_in_network"),
                "fh_facility_hosp_in_network": rate.get("fh_facility_hosp_in_network"),
                "fh_pathology_in_network": rate.get("fh_pathology_in_network"),
                # Service info
                "cpt": cpt,
                "cpt_desc": rate.get("cpt_desc", ""),
            }
        )

    results.sort(key=lambda x: x["doctor_count"], reverse=True)
    return results


@router.get("/payment-table")
def get_payment_table(
    plan_id: str | None = Query(None),
    cpt: str | None = Query(None),
    hospital_id: str | None = Query(None),
    scenario_id: str | None = Query(None),
    specialty: str | None = Query(None),
) -> list[dict[str, Any]]:
    """Pre-computed OOP estimates per plan × hospital × scenario.

    Returns two scenarios: A (deductible fully remaining) and B (deductible met).
    Filter by any combination of plan_id, cpt, hospital_id, scenario_id, specialty.
    """
    results = _PAYMENT_TABLE
    if plan_id:
        results = [r for r in results if r["plan_id"] == plan_id]
    if cpt:
        results = [r for r in results if r["cpt"] == cpt]
    if hospital_id:
        results = [r for r in results if r["hospital_id"] == hospital_id]
    if scenario_id:
        results = [r for r in results if r["scenario_id"] == scenario_id]
    if specialty:
        results = [r for r in results if r["specialty"].lower() == specialty.lower()]
    return results
